# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos.rag.v1 import paper_rag_index_pb2 as app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/rag/v1/paper_rag_index_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaperRagIndexInternalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnsurePaperRagIndexes = channel.unary_unary(
                '/papercollector.rag.v1.PaperRagIndexInternalService/EnsurePaperRagIndexes',
                request_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.EnsurePaperRagIndexesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.EnsurePaperRagIndexesResponse.FromString,
                _registered_method=True)
        self.ClaimPaperRagIndexes = channel.unary_unary(
                '/papercollector.rag.v1.PaperRagIndexInternalService/ClaimPaperRagIndexes',
                request_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.ClaimPaperRagIndexesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.ClaimPaperRagIndexesResponse.FromString,
                _registered_method=True)
        self.CompletePaperRagIndex = channel.unary_unary(
                '/papercollector.rag.v1.PaperRagIndexInternalService/CompletePaperRagIndex',
                request_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.CompletePaperRagIndexRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.CompletePaperRagIndexResponse.FromString,
                _registered_method=True)
        self.GetPaperRagIndexes = channel.unary_unary(
                '/papercollector.rag.v1.PaperRagIndexInternalService/GetPaperRagIndexes',
                request_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.GetPaperRagIndexesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.GetPaperRagIndexesResponse.FromString,
                _registered_method=True)
        self.SkipPaperRagIndexes = channel.unary_unary(
                '/papercollector.rag.v1.PaperRagIndexInternalService/SkipPaperRagIndexes',
                request_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.SkipPaperRagIndexesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.SkipPaperRagIndexesResponse.FromString,
                _registered_method=True)


class PaperRagIndexInternalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EnsurePaperRagIndexes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimPaperRagIndexes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompletePaperRagIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaperRagIndexes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkipPaperRagIndexes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaperRagIndexInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnsurePaperRagIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsurePaperRagIndexes,
                    request_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.EnsurePaperRagIndexesRequest.FromString,
                    response_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.EnsurePaperRagIndexesResponse.SerializeToString,
            ),
            'ClaimPaperRagIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimPaperRagIndexes,
                    request_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.ClaimPaperRagIndexesRequest.FromString,
                    response_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.ClaimPaperRagIndexesResponse.SerializeToString,
            ),
            'CompletePaperRagIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CompletePaperRagIndex,
                    request_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.CompletePaperRagIndexRequest.FromString,
                    response_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.CompletePaperRagIndexResponse.SerializeToString,
            ),
            'GetPaperRagIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaperRagIndexes,
                    request_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.GetPaperRagIndexesRequest.FromString,
                    response_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.GetPaperRagIndexesResponse.SerializeToString,
            ),
            'SkipPaperRagIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.SkipPaperRagIndexes,
                    request_deserializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.SkipPaperRagIndexesRequest.FromString,
                    response_serializer=app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.SkipPaperRagIndexesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'papercollector.rag.v1.PaperRagIndexInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('papercollector.rag.v1.PaperRagIndexInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaperRagIndexInternalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnsurePaperRagIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.rag.v1.PaperRagIndexInternalService/EnsurePaperRagIndexes',
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.EnsurePaperRagIndexesRequest.SerializeToString,
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.EnsurePaperRagIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimPaperRagIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.rag.v1.PaperRagIndexInternalService/ClaimPaperRagIndexes',
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.ClaimPaperRagIndexesRequest.SerializeToString,
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.ClaimPaperRagIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompletePaperRagIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.rag.v1.PaperRagIndexInternalService/CompletePaperRagIndex',
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.CompletePaperRagIndexRequest.SerializeToString,
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.CompletePaperRagIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaperRagIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.rag.v1.PaperRagIndexInternalService/GetPaperRagIndexes',
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.GetPaperRagIndexesRequest.SerializeToString,
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.GetPaperRagIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkipPaperRagIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.rag.v1.PaperRagIndexInternalService/SkipPaperRagIndexes',
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.SkipPaperRagIndexesRequest.SerializeToString,
            app_dot_protos_dot_rag_dot_v1_dot_paper__rag__index__pb2.SkipPaperRagIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
