# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos.rag.v1 import rag_pb2 as app_dot_protos_dot_rag_dot_v1_dot_rag__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/rag/v1/rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagInternalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClaimTaskRagPapers = channel.unary_unary(
                '/papercollector.rag.v1.RagInternalService/ClaimTaskRagPapers',
                request_serializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.ClaimTaskRagPapersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.ClaimTaskRagPapersResponse.FromString,
                _registered_method=True)
        self.CompleteTaskRagBatch = channel.unary_unary(
                '/papercollector.rag.v1.RagInternalService/CompleteTaskRagBatch',
                request_serializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.CompleteTaskRagBatchRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.CompleteTaskRagBatchResponse.FromString,
                _registered_method=True)


class RagInternalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ClaimTaskRagPapers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTaskRagBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClaimTaskRagPapers': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTaskRagPapers,
                    request_deserializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.ClaimTaskRagPapersRequest.FromString,
                    response_serializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.ClaimTaskRagPapersResponse.SerializeToString,
            ),
            'CompleteTaskRagBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTaskRagBatch,
                    request_deserializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.CompleteTaskRagBatchRequest.FromString,
                    response_serializer=app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.CompleteTaskRagBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'papercollector.rag.v1.RagInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('papercollector.rag.v1.RagInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagInternalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClaimTaskRagPapers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.rag.v1.RagInternalService/ClaimTaskRagPapers',
            app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.ClaimTaskRagPapersRequest.SerializeToString,
            app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.ClaimTaskRagPapersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTaskRagBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.rag.v1.RagInternalService/CompleteTaskRagBatch',
            app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.CompleteTaskRagBatchRequest.SerializeToString,
            app_dot_protos_dot_rag_dot_v1_dot_rag__pb2.CompleteTaskRagBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
