# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos.task.v1 import task_pb2 as app_dot_protos_dot_task_dot_v1_dot_task__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/task/v1/task_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskInternalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddQueryTask = channel.unary_unary(
                '/papercollector.task.v1.TaskInternalService/AddQueryTask',
                request_serializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.AddQueryTaskRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.AddQueryTaskResponse.FromString,
                _registered_method=True)
        self.UpdateTaskStatus = channel.unary_unary(
                '/papercollector.task.v1.TaskInternalService/UpdateTaskStatus',
                request_serializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.UpdateTaskStatusRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.UpdateTaskStatusResponse.FromString,
                _registered_method=True)
        self.BatchSaveTaskPaperRelations = channel.unary_unary(
                '/papercollector.task.v1.TaskInternalService/BatchSaveTaskPaperRelations',
                request_serializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.BatchSaveTaskPaperRelationsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.BatchSaveTaskPaperRelationsResponse.FromString,
                _registered_method=True)


class TaskInternalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AddQueryTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSaveTaskPaperRelations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddQueryTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddQueryTask,
                    request_deserializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.AddQueryTaskRequest.FromString,
                    response_serializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.AddQueryTaskResponse.SerializeToString,
            ),
            'UpdateTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskStatus,
                    request_deserializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.UpdateTaskStatusRequest.FromString,
                    response_serializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.UpdateTaskStatusResponse.SerializeToString,
            ),
            'BatchSaveTaskPaperRelations': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSaveTaskPaperRelations,
                    request_deserializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.BatchSaveTaskPaperRelationsRequest.FromString,
                    response_serializer=app_dot_protos_dot_task_dot_v1_dot_task__pb2.BatchSaveTaskPaperRelationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'papercollector.task.v1.TaskInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('papercollector.task.v1.TaskInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskInternalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddQueryTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.task.v1.TaskInternalService/AddQueryTask',
            app_dot_protos_dot_task_dot_v1_dot_task__pb2.AddQueryTaskRequest.SerializeToString,
            app_dot_protos_dot_task_dot_v1_dot_task__pb2.AddQueryTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.task.v1.TaskInternalService/UpdateTaskStatus',
            app_dot_protos_dot_task_dot_v1_dot_task__pb2.UpdateTaskStatusRequest.SerializeToString,
            app_dot_protos_dot_task_dot_v1_dot_task__pb2.UpdateTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSaveTaskPaperRelations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.task.v1.TaskInternalService/BatchSaveTaskPaperRelations',
            app_dot_protos_dot_task_dot_v1_dot_task__pb2.BatchSaveTaskPaperRelationsRequest.SerializeToString,
            app_dot_protos_dot_task_dot_v1_dot_task__pb2.BatchSaveTaskPaperRelationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
