# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos.task_paper_relation.v1 import task_paper_relation_pb2 as app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/task_paper_relation/v1/task_paper_relation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskPaperRelationInternalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUnindexedPaperRagInfosByTaskId = channel.unary_unary(
                '/papercollector.taskpaperrelation.v1.TaskPaperRelationInternalService/GetUnindexedPaperRagInfosByTaskId',
                request_serializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.GetUnindexedPaperRagInfosByTaskIdResponse.FromString,
                _registered_method=True)
        self.GetPaperIdsByTaskId = channel.unary_unary(
                '/papercollector.taskpaperrelation.v1.TaskPaperRelationInternalService/GetPaperIdsByTaskId',
                request_serializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.GetPaperIdsByTaskIdResponse.FromString,
                _registered_method=True)


class TaskPaperRelationInternalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUnindexedPaperRagInfosByTaskId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaperIdsByTaskId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskPaperRelationInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUnindexedPaperRagInfosByTaskId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnindexedPaperRagInfosByTaskId,
                    request_deserializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.TaskIdRequest.FromString,
                    response_serializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.GetUnindexedPaperRagInfosByTaskIdResponse.SerializeToString,
            ),
            'GetPaperIdsByTaskId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaperIdsByTaskId,
                    request_deserializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.TaskIdRequest.FromString,
                    response_serializer=app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.GetPaperIdsByTaskIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'papercollector.taskpaperrelation.v1.TaskPaperRelationInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('papercollector.taskpaperrelation.v1.TaskPaperRelationInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskPaperRelationInternalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUnindexedPaperRagInfosByTaskId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.taskpaperrelation.v1.TaskPaperRelationInternalService/GetUnindexedPaperRagInfosByTaskId',
            app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.TaskIdRequest.SerializeToString,
            app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.GetUnindexedPaperRagInfosByTaskIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaperIdsByTaskId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.taskpaperrelation.v1.TaskPaperRelationInternalService/GetPaperIdsByTaskId',
            app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.TaskIdRequest.SerializeToString,
            app_dot_protos_dot_task__paper__relation_dot_v1_dot_task__paper__relation__pb2.GetPaperIdsByTaskIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
