# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/task_paper_relation/v1/task_paper_relation.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'app/protos/task_paper_relation/v1/task_paper_relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;app/protos/task_paper_relation/v1/task_paper_relation.proto\x12#papercollector.taskpaperrelation.v1\x1a\x1cgoogle/protobuf/struct.proto\" \n\rTaskIdRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x03\"X\n\x10PaperRagInfoItem\x12\x10\n\x08paper_id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x16\n\x0epaper_abstract\x18\x04 \x01(\t\"\xe0\x01\n)GetUnindexedPaperRagInfosByTaskIdResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07task_id\x18\x03 \x01(\x03\x12J\n\x0bpaper_infos\x18\x04 \x03(\x0b\x32\x35.papercollector.taskpaperrelation.v1.PaperRagInfoItem\x12\x0f\n\x07message\x18\x05 \x01(\t\x12&\n\x05other\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x88\x01\n\x1bGetPaperIdsByTaskIdResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x11\n\tpaper_ids\x18\x03 \x03(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t\x12&\n\x05other\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct2\xda\x02\n TaskPaperRelationInternalService\x12\xa7\x01\n!GetUnindexedPaperRagInfosByTaskId\x12\x32.papercollector.taskpaperrelation.v1.TaskIdRequest\x1aN.papercollector.taskpaperrelation.v1.GetUnindexedPaperRagInfosByTaskIdResponse\x12\x8b\x01\n\x13GetPaperIdsByTaskId\x12\x32.papercollector.taskpaperrelation.v1.TaskIdRequest\x1a@.papercollector.taskpaperrelation.v1.GetPaperIdsByTaskIdResponseB1\n-com.yl.paperservice.grpc.taskpaperrelation.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.task_paper_relation.v1.task_paper_relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.yl.paperservice.grpc.taskpaperrelation.v1P\001'
  _globals['_TASKIDREQUEST']._serialized_start=130
  _globals['_TASKIDREQUEST']._serialized_end=162
  _globals['_PAPERRAGINFOITEM']._serialized_start=164
  _globals['_PAPERRAGINFOITEM']._serialized_end=252
  _globals['_GETUNINDEXEDPAPERRAGINFOSBYTASKIDRESPONSE']._serialized_start=255
  _globals['_GETUNINDEXEDPAPERRAGINFOSBYTASKIDRESPONSE']._serialized_end=479
  _globals['_GETPAPERIDSBYTASKIDRESPONSE']._serialized_start=482
  _globals['_GETPAPERIDSBYTASKIDRESPONSE']._serialized_end=618
  _globals['_TASKPAPERRELATIONINTERNALSERVICE']._serialized_start=621
  _globals['_TASKPAPERRELATIONINTERNALSERVICE']._serialized_end=967
# @@protoc_insertion_point(module_scope)
