# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos.venue.v1 import venue_pb2 as app_dot_protos_dot_venue_dot_v1_dot_venue__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/venue/v1/venue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VenueInternalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveVenue = channel.unary_unary(
                '/papercollector.venue.v1.VenueInternalService/SaveVenue',
                request_serializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.SaveVenueRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.SaveVenueResponse.FromString,
                _registered_method=True)
        self.BatchSaveVenues = channel.unary_unary(
                '/papercollector.venue.v1.VenueInternalService/BatchSaveVenues',
                request_serializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.BatchSaveVenuesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.BatchSaveVenuesResponse.FromString,
                _registered_method=True)


class VenueInternalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SaveVenue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSaveVenues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VenueInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveVenue': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveVenue,
                    request_deserializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.SaveVenueRequest.FromString,
                    response_serializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.SaveVenueResponse.SerializeToString,
            ),
            'BatchSaveVenues': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSaveVenues,
                    request_deserializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.BatchSaveVenuesRequest.FromString,
                    response_serializer=app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.BatchSaveVenuesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'papercollector.venue.v1.VenueInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('papercollector.venue.v1.VenueInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VenueInternalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveVenue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.venue.v1.VenueInternalService/SaveVenue',
            app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.SaveVenueRequest.SerializeToString,
            app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.SaveVenueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSaveVenues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.venue.v1.VenueInternalService/BatchSaveVenues',
            app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.BatchSaveVenuesRequest.SerializeToString,
            app_dot_protos_dot_venue_dot_v1_dot_venue__pb2.BatchSaveVenuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
