# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/venue/v1/venue.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'app/protos/venue/v1/venue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61pp/protos/venue/v1/venue.proto\x12\x17papercollector.venue.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd3\x01\n\x10SaveVenueRequest\x12\x15\n\rstandard_name\x18\x01 \x01(\t\x12\x11\n\x04type\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x0f\n\x07\x61\x63ronym\x18\x03 \x01(\t\x12\x10\n\x08sci_rank\x18\x04 \x01(\t\x12\x10\n\x08\x63\x63\x66_rank\x18\x05 \x01(\t\x12\x13\n\x06sci_if\x18\x06 \x01(\x01H\x01\x88\x01\x01\x12\x0e\n\x06sci_up\x18\x07 \x01(\t\x12\x14\n\x0csci_up_small\x18\x08 \x01(\t\x12\x11\n\tcore_rank\x18\t \x01(\tB\x07\n\x05_typeB\t\n\x07_sci_if\"\x96\x01\n\x11SaveVenueResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12)\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x0f\n\x07message\x18\x04 \x01(\t\x12&\n\x05other\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"S\n\x16\x42\x61tchSaveVenuesRequest\x12\x39\n\x06venues\x18\x01 \x03(\x0b\x32).papercollector.venue.v1.SaveVenueRequest\"0\n\x0bVenueIdItem\x12\x15\n\rstandard_name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\"\xa5\x01\n\x17\x42\x61tchSaveVenuesResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x32\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32$.papercollector.venue.v1.VenueIdItem\x12\x0f\n\x07message\x18\x04 \x01(\t\x12&\n\x05other\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct2\xf0\x01\n\x14VenueInternalService\x12\x62\n\tSaveVenue\x12).papercollector.venue.v1.SaveVenueRequest\x1a*.papercollector.venue.v1.SaveVenueResponse\x12t\n\x0f\x42\x61tchSaveVenues\x12/.papercollector.venue.v1.BatchSaveVenuesRequest\x1a\x30.papercollector.venue.v1.BatchSaveVenuesResponseB%\n!com.yl.paperservice.grpc.venue.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.venue.v1.venue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.yl.paperservice.grpc.venue.v1P\001'
  _globals['_SAVEVENUEREQUEST']._serialized_start=123
  _globals['_SAVEVENUEREQUEST']._serialized_end=334
  _globals['_SAVEVENUERESPONSE']._serialized_start=337
  _globals['_SAVEVENUERESPONSE']._serialized_end=487
  _globals['_BATCHSAVEVENUESREQUEST']._serialized_start=489
  _globals['_BATCHSAVEVENUESREQUEST']._serialized_end=572
  _globals['_VENUEIDITEM']._serialized_start=574
  _globals['_VENUEIDITEM']._serialized_end=622
  _globals['_BATCHSAVEVENUESRESPONSE']._serialized_start=625
  _globals['_BATCHSAVEVENUESRESPONSE']._serialized_end=790
  _globals['_VENUEINTERNALSERVICE']._serialized_start=793
  _globals['_VENUEINTERNALSERVICE']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
