# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos.paper.v1 import paper_pb2 as app_dot_protos_dot_paper_dot_v1_dot_paper__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/paper/v1/paper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaperInternalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExistingPapers = channel.unary_unary(
                '/papercollector.paper.v1.PaperInternalService/GetExistingPapers',
                request_serializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetExistingPapersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetExistingPapersResponse.FromString,
                _registered_method=True)
        self.BatchSavePapers = channel.unary_unary(
                '/papercollector.paper.v1.PaperInternalService/BatchSavePapers',
                request_serializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.BatchSavePapersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.BatchSavePapersResponse.FromString,
                _registered_method=True)
        self.GetTaskReviewPapers = channel.unary_unary(
                '/papercollector.paper.v1.PaperInternalService/GetTaskReviewPapers',
                request_serializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetTaskReviewPapersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetTaskReviewPapersResponse.FromString,
                _registered_method=True)


class PaperInternalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetExistingPapers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSavePapers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskReviewPapers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaperInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExistingPapers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExistingPapers,
                    request_deserializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetExistingPapersRequest.FromString,
                    response_serializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetExistingPapersResponse.SerializeToString,
            ),
            'BatchSavePapers': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSavePapers,
                    request_deserializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.BatchSavePapersRequest.FromString,
                    response_serializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.BatchSavePapersResponse.SerializeToString,
            ),
            'GetTaskReviewPapers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskReviewPapers,
                    request_deserializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetTaskReviewPapersRequest.FromString,
                    response_serializer=app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetTaskReviewPapersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'papercollector.paper.v1.PaperInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('papercollector.paper.v1.PaperInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaperInternalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExistingPapers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.paper.v1.PaperInternalService/GetExistingPapers',
            app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetExistingPapersRequest.SerializeToString,
            app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetExistingPapersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSavePapers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.paper.v1.PaperInternalService/BatchSavePapers',
            app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.BatchSavePapersRequest.SerializeToString,
            app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.BatchSavePapersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskReviewPapers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/papercollector.paper.v1.PaperInternalService/GetTaskReviewPapers',
            app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetTaskReviewPapersRequest.SerializeToString,
            app_dot_protos_dot_paper_dot_v1_dot_paper__pb2.GetTaskReviewPapersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
