# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/review/v1/review.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'app/protos/review/v1/review.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!app/protos/review/v1/review.proto\x12\x18papercollector.review.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x8d\x03\n\x10\x41\x64\x64ReviewRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x03\x12\r\n\x05topic\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x16\n\x0eversion_number\x18\x04 \x01(\x05\x12\x10\n\x08language\x18\x05 \x01(\t\x12\x13\n\x0breview_type\x18\x06 \x01(\x05\x12\x16\n\x0e\x63itation_style\x18\x07 \x01(\x05\x12\r\n\x05scope\x18\x08 \x01(\t\x12\x18\n\x10\x61\x62stract_content\x18\t \x01(\t\x12\x15\n\rbody_markdown\x18\n \x01(\t\x12\x12\n\nconclusion\x18\x0b \x01(\t\x12\x10\n\x08markdown\x18\x0c \x01(\t\x12\x10\n\x08sections\x18\r \x01(\t\x12\x1a\n\x12paper_ids_snapshot\x18\x0e \x01(\t\x12\x1a\n\x12\x63itation_paper_ids\x18\x0f \x01(\t\x12\x17\n\x0f\x63itation_labels\x18\x10 \x01(\t\x12\x12\n\nreferences\x18\x11 \x01(\t\x12\x16\n\x0e\x66ramework_hash\x18\x12 \x01(\t\"\x96\x01\n\x11\x41\x64\x64ReviewResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x11\n\treview_id\x18\x03 \x01(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t\x12&\n\x05other\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x16\n\x0eversion_number\x18\x06 \x01(\x05\x32}\n\x15ReviewInternalService\x12\x64\n\tAddReview\x12*.papercollector.review.v1.AddReviewRequest\x1a+.papercollector.review.v1.AddReviewResponseB&\n\"com.yl.paperservice.grpc.review.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.review.v1.review_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.yl.paperservice.grpc.review.v1P\001'
  _globals['_ADDREVIEWREQUEST']._serialized_start=94
  _globals['_ADDREVIEWREQUEST']._serialized_end=491
  _globals['_ADDREVIEWRESPONSE']._serialized_start=494
  _globals['_ADDREVIEWRESPONSE']._serialized_end=644
  _globals['_REVIEWINTERNALSERVICE']._serialized_start=646
  _globals['_REVIEWINTERNALSERVICE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
